// BIG WIGGLE
exports.printMsg = function() {
  console.log("Big WIGGLE loaded");
}

const bigWiggle = (wiggleText) => {
  return `${wiggleText}\n ${wiggleText}\n  ${wiggleText}\n   ${wiggleText}\n     ${wiggleText}\n       ${wiggleText}\n         ${wiggleText}\n            ${wiggleText}\n               ${wiggleText}\n                  ${wiggleText}\n                     ${wiggleText}\n                        ${wiggleText}\n                           ${wiggleText}\n                              ${wiggleText}\n                                 ${wiggleText}\n                                    ${wiggleText}\n                                       ${wiggleText}\n                                         ${wiggleText}\n                                           ${wiggleText}\n                                             ${wiggleText}\n                                              ${wiggleText}\n                                               ${wiggleText}\n                                                ${wiggleText}\n                                                ${wiggleText}\n                                                ${wiggleText}\n                                                ${wiggleText}\n                                               ${wiggleText}\n                                              ${wiggleText}\n                                             ${wiggleText}\n                                           ${wiggleText}\n                                         ${wiggleText}\n                                       ${wiggleText}\n                                    ${wiggleText}\n                                 ${wiggleText}\n                              ${wiggleText}\n                           ${wiggleText}\n                        ${wiggleText}\n                     ${wiggleText}\n                  ${wiggleText}\n               ${wiggleText}\n            ${wiggleText}\n         ${wiggleText}\n       ${wiggleText}\n     ${wiggleText}\n   ${wiggleText}\n  ${wiggleText}\n ${wiggleText}\n${wiggleText}\n`;
}

function bigwiggle(wiggleText) {
  return `${wiggleText}\n ${wiggleText}\n  ${wiggleText}\n   ${wiggleText}\n     ${wiggleText}\n       ${wiggleText}\n         ${wiggleText}\n            ${wiggleText}\n               ${wiggleText}\n                  ${wiggleText}\n                     ${wiggleText}\n                        ${wiggleText}\n                           ${wiggleText}\n                              ${wiggleText}\n                                 ${wiggleText}\n                                    ${wiggleText}\n                                       ${wiggleText}\n                                         ${wiggleText}\n                                           ${wiggleText}\n                                             ${wiggleText}\n                                              ${wiggleText}\n                                               ${wiggleText}\n                                                ${wiggleText}\n                                                ${wiggleText}\n                                                ${wiggleText}\n                                                ${wiggleText}\n                                               ${wiggleText}\n                                              ${wiggleText}\n                                             ${wiggleText}\n                                           ${wiggleText}\n                                         ${wiggleText}\n                                       ${wiggleText}\n                                    ${wiggleText}\n                                 ${wiggleText}\n                              ${wiggleText}\n                           ${wiggleText}\n                        ${wiggleText}\n                     ${wiggleText}\n                  ${wiggleText}\n               ${wiggleText}\n            ${wiggleText}\n         ${wiggleText}\n       ${wiggleText}\n     ${wiggleText}\n   ${wiggleText}\n  ${wiggleText}\n ${wiggleText}\n${wiggleText}\n`
}

module.exports.bigWiggle = bigWiggle;
